config/routes.rb
Rails.application.routes.draw do

  root 'homes#index'

     resources :homes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    if  params[:home]
       if  params[:home][:action] == "sum"
        sum
       end
    end
  end

  private
  def sum
    if  params[:home]
      @a = params[:home][:a].to_i
      @b = params[:home][:b].to_i
      @c = @a+@b
    end
  end
end

app/controllers/rpc_hosts_controller.rb
class RpcHostsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rpc_hosts_helper.rb
module RpcHostsHelper
end

app/views/homes/_form.html.erb
<%= form_for :home, url: homes_path, html: {id: "ajax_form"},
  method: :get, remote: true do |f| %>
  <%= f.label :A %>
  <%= f.text_field :a, class: 'form-control', value: @a %>
  <%= f.label :B %>
  <%= f.text_field :b, class: 'form-control', value: @b %>
  <%= f.label "A+B" %>
  <%= f.text_field :c, class: 'form-control', value: @c %>
  <%= f.hidden_field :action, class: 'form-control', value: :sum %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

<script>
$('#ajax_form').on('ajax:success', function(event, data, status, xhr) {
  alert('success');
});

$('#ajax_form').on('ajax:error', function(event, xhr, status, error) {
  alert('error');
});

$('#ajax_form').on('ajax:beforeSend', function(event, xhr, settings) {
    alert('beforeSend');
});
</script>

app/views/homes/index.html.erb
<div id="c">
  <%= render "form" %>
</div>

app/views/homes/index.js.erb
$("#c").html("<%= escape_javascript(render 'form') %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AjaxRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>